### ISSUE TITLE
Connection object is successful only through callback consumption

### ISSUE THREAD

**Issue by barberousse** [jacott/node-pg-libpq#3]
First off, thanks for the library. I’m currently attempting to escape ORM hell and your library is situated perfectly, as you note, between node-pg and node-libpq. However, I’m encountering an issue wherein the connection object is never in a READY state when consuming the library as a Promise API, but connects successfully and is in a READY state when consumed via the callback interface. Looking at your source, it seems this just shouldn’t be happening, so perhaps theres an error on my part. So then, this ends up failing:
```javascript
const PG = require('pg-libpq')
const SQL_PATH = `${process.cwd()}/migrations/sql`
const DATABASE_URL = process.env.DATABASE_URL
const { log, map, readAll, asynchronize } = require('../utils')

const pg = new PG(DATABASE_URL)

readAll(SQL_PATH)
  .then(files => map(file => file.toString(), files))
  .then(statements => asynchronize(migrate, pg, statements)) // asynchronize === co
  .catch(err => log(err))


function* migrate (client, statements) {
  log(client.isReady()) // FALSE, subsequent yield errs with connection not in ready state
  while(statements.length) {
    const statement = statements.unshift()
    const result = yield client.exec(statement)
    log(result)
  }
  client.finish()
}
```

But this shows up READY:

```javascript
const PG = require('pg-libpq')
const SQL_PATH = `${process.cwd()}/migrations/sql`
const DATABASE_URL = process.env.DATABASE_URL
const { log, map, readAll, asynchronize } = require('../utils')

const pg = new PG(DATABASE_URL, (err, client) => log(client.isReady())) // TRUE

**Comment by vitaly-t** [comment]
@barberousse have you tried [pg-promise](https://github.com/vitaly-t/pg-promise)? You can use it with the Native Binding just the same ;)

**Comment by barberousse** [comment]
@vitaly-t Thanks for the tip, your library worked out great

**Comment by jacott** [comment]
pg-libpq requires the connection to be ready before making a call -- I'm looking at changing this -- so your promise code needs to be written like so:

```js
const pg = new PG(DATABASE_URL)
pg
  .then(() => readAll(SQL_PATH))
  .then(files => map(file => file.toString(), files))
  .then(statements => asynchronize(migrate, pg, statements)) // asynchronize === co
  .catch(err => log(err))
```

**Comment by barberousse** [comment]
Wow, missed that initial then call to the library. Whoops. Thanks @jacott

**Comment by jacott** [comment]
I've updated the package so that commands will queue if connection is not ready. This means your original code should work without needing to call `pg.then(...)`
