### ISSUE TITLE
Using with Slonik

### ISSUE THREAD

**Issue by gajus** [jacott/node-pg-libpq#5]
I am considering adopting pg-libpq in https://github.com/gajus/slonik. Currently, using https://github.com/brianc/node-postgres doesn't provide any sizeable benefits given our existing abstraction.

Anything I should be aware of before attempting the transition?

The primary reason for testing `pg-libpq` is performance and issues such as this one https://github.com/brianc/node-postgres/issues/980.

**Comment by jacott** [comment]
Sorry @gajus for taking so long to answer your question.

nulls in binary objects are okay. I am not aware of any problems transitioning to pg-libpq.
